title: Vaibhav Jain
description: > Crafting tomorrow's data-driven narratives today, I'm the Data Engineer turning information into innovation with a blend of tech savvy and strategic prowess.
logo: /images/linkedin_photo.jpeg
theme: jekyll-theme-minimal
